# Generated by Django 3.0.5 on 2020-07-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('logo_uri', models.ImageField(upload_to='pics')),
                ('club_state', models.CharField(max_length=200)),
            ],
        ),
    ]
