# Generated by Django 3.0.5 on 2020-07-03 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image_uri', models.ImageField(upload_to='pics')),
                ('jersey_number', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.Team')),
            ],
        ),
    ]
