# Generated by Django 3.0.5 on 2020-07-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_A', models.CharField(max_length=200)),
                ('team_B', models.CharField(max_length=200)),
                ('stadium', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('winner', models.CharField(max_length=200)),
            ],
        ),
    ]
