# Generated by Django 3.0.5 on 2020-07-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='team_A',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='team_B',
        ),
        migrations.AddField(
            model_name='matches',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='teams',
            field=models.ManyToManyField(to='Teams.Team'),
        ),
    ]
